apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: server
  template:
    metadata:
      labels:
        service: server
    spec:
      containers:
        - name: server-service
          image: ksobitov/petclinic-springboot
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-entrypoint
  namespace: default 
spec:
  type: NodePort
  selector:
    service: server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
